"""empty message

Revision ID: 1f6b0eba3152
Revises: 9baecab3227c
Create Date: 2018-11-18 22:03:01.693580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6b0eba3152'
down_revision = '9baecab3227c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('likes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'likes')
    # ### end Alembic commands ###
