"""empty message

Revision ID: 797a05ab4b83
Revises: 1f6b0eba3152
Create Date: 2018-11-19 13:17:42.431397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797a05ab4b83'
down_revision = '1f6b0eba3152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('post_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'post_id')
    # ### end Alembic commands ###
