"""empty message

Revision ID: 9baecab3227c
Revises: 54bd0f7227e0
Create Date: 2018-11-18 20:07:44.124918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9baecab3227c'
down_revision = '54bd0f7227e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('post', sa.Column('header', sa.String(length=30), nullable=True))
    op.add_column('post', sa.Column('rating', sa.String(length=1000000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'rating')
    op.drop_column('post', 'header')
    op.drop_table('comment')
    # ### end Alembic commands ###
