"""empty message

Revision ID: c89ad9ed312f
Revises: 797a05ab4b83
Create Date: 2018-11-20 01:18:38.755140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c89ad9ed312f'
down_revision = '797a05ab4b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_post_last_seen'), 'post', ['last_seen'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_last_seen'), table_name='post')
    op.drop_column('post', 'last_seen')
    # ### end Alembic commands ###
