"""empty message

Revision ID: f55129cc5c65
Revises: c89ad9ed312f
Create Date: 2018-11-20 10:03:36.685731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f55129cc5c65'
down_revision = 'c89ad9ed312f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_last_seen', table_name='post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_post_last_seen', 'post', ['last_seen'], unique=False)
    # ### end Alembic commands ###
